sonar.projectKey=SaiPawan01_Customer-Support-Chatbot
sonar.organization=saipawan01

sonar.sources=backend
sonar.tests=backend
sonar.test.inclusions=backend/**/tests.py
sonar.exclusions=backend/**/migrations/**,backend/**/__pycache__/**,backend/**/*.pyi,frontend/**,chatbot-widget/**,**/.venv/**,**/venv/**
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.sourceEncoding=UTF-8