# Generated by Django 6.0.2 on 2026-02-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
