# Generated by Django 6.0.2 on 2026-02-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_message_sender_alter_message_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
    ]
