# Generated by Django 6.0.2 on 2026-03-09 04:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_conversation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='source',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True),
        ),
    ]
