# Generated by Django 6.0.2 on 2026-04-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_message_confidence_score'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE chatbot_message ALTER COLUMN source TYPE jsonb USING CASE WHEN source IS NULL THEN NULL ELSE to_jsonb(source) END",
            reverse_sql="ALTER TABLE chatbot_message ALTER COLUMN source TYPE varchar(100)[] USING CASE WHEN source IS NULL THEN NULL ELSE source::varchar(100)[] END"
        ),
        migrations.AlterField(
            model_name='message',
            name='source',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
